### ISSUE TITLE
The FIPE Side Meeting @IETF108

### ISSUE THREAD

**Issue by FIPE-Study** [FIPE-Study/IETF108-Side-Meeting-FIPE#1]
### **Meeting**
Title: Future Internet Protocol Evolution (FIPE)
Time:  07/31/2020, 15:00 - 16:30 UTC (extend to 17:00 if needed)
                                   Participants can join up to 15 minutes earlier, e.g.: for webex testing
Where: Webex

### **Goal**
The goal of this inofficial side meeting is to make progress on defining research challenges and problems related to Future Internet Protocol Evolution (FIPE) that are not already better covered by other IRTF RG. We welcome any proposals and discussions to that end. 

### **Tentative Agenda**

1. Multi-Semantic Addressing Enable Interconnection of IOT and Heterogeneous Networks ( 25 mins + 15mins )
- Various networks, such as  IoT networks, industry networks, satellite networks, etc.
- Interconnection of heterogeneous networks
- Challenges/Problems to Internet Protocols
- ...

2. High Precision Assurance ( 20 mins )
- New services, such as online meeting, 3D, VR/AR, holy graphic, etc. The critical payloads should affirmatively arrive “on time”
- Challenges/Problems on IP layer, transport layer, data plane, etc.
- ...

3. Problems of Security ( 20 mins )
- Conflicted requirements of privacy protection vs. network accountability
- Generic security in network-layer vs. application-layer
- More impact of security middle box for interworking
- ...

**Comment by toerless** [comment]
Copied issue into README.md, added pointer to etherpad.
Issue closed
